//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalletLesster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Merchant { get; set; }
        public string Category { get; set; }
        public double Amount { get; set; }
        public System.DateTime Date { get; set; }
        public bool Recurrence { get; set; }
        public int UserId { get; set; }
        public int CategoryId { get; set; }
        public int MerchantId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Category Category1 { get; set; }
        public virtual Merchant Merchant1 { get; set; }
    }
}
